CREATE TABLE budget_transactions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date TIMESTAMP NOT NULL DEFAULT now(),
    payee TEXT,
    memo TEXT,
    outflow INT,
    inflow INT
);


ALTER TABLE budget_transactions
    ADD COLUMN
        account_id INT REFERENCES budget_accounts(id)
        ON DELETE SET NULL;

-- did this work? make it so one must be not null 
ALTER TABLE budget_transactions
    ADD CONSTRAINT 
        isNotNull CHECK 
        (outflow IS NOT NULL OR inflow IS NOT NULL);