CREATE TABLE budget_subcategories (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    budgeted INT,
    spent INT
);

ALTER TABLE budget_subcategories
    ADD COLUMN
        category_id INT REFERENCES budget_categories(id)
        ON DELETE SET NULL;

ALTER TABLE budget_transactions
    ADD COLUMN
        subcategory_id INT REFERENCES budget_subcategories(id)
        ON DELETE SET NULL;