CREATE TABLE budget_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);

ALTER TABLE budget_accounts
  ADD COLUMN
    user_id INTEGER REFERENCES budget_users(id)
    ON DELETE CASCADE NOT NULL;

ALTER TABLE budget_categories
  ADD COLUMN
    user_id INTEGER REFERENCES budget_users(id)
    ON DELETE CASCADE NOT NULL;

ALTER TABLE budget_subcategories
  ADD COLUMN
    user_id INTEGER REFERENCES budget_users(id)
    ON DELETE CASCADE NOT NULL;

ALTER TABLE budget_transactions
  ADD COLUMN
    user_id INTEGER REFERENCES budget_users(id)
    ON DELETE CASCADE NOT NULL;